"""Generate the dbt files that mirror the table specs, so contracts are written once.

Outputs (committed, regenerated by ``bank-data codegen``, checked by ``bank-data codegen --check`` and a test):

- ``dbt/models/sources.yml``: the bronze sources with their external location, freshness, and column metadata
  (type, canonical domain, foreign key) that the silver macros read;
- ``dbt/models/silver/_silver.yml``: the enforced contracts and tests of every ``stg_`` and ``silver_`` model;
- ``dbt/seeds/canonical_values.csv``: the translations from source values to canonical codes.
"""

import csv
import io
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from bank_data.config import SourceConfig
from bank_data.contracts.canonical import TRANSLATIONS, canonical_codes, seed_rows
from bank_data.contracts.tables import CONTRACT_VERSION, TABLES, ColumnSpec, TableSpec

HEADER = "# Generated by `bank-data codegen` from bank_data.contracts.tables. Do not edit by hand.\n"
STG_LINEAGE: tuple[tuple[str, str], ...] = (
    ("_source_key", "varchar"),
    ("_etag", "varchar"),
    ("_loaded_at", "timestamp"),
    ("_process_date", "date"),
    ("_source_row", "bigint"),
)
ISO_COUNTRIES = tuple(dict.fromkeys(TRANSLATIONS["country"].values()))

EVENT_TIMESTAMPS: dict[str, tuple[str, int]] = {
    "transactions": ("transaction_date", 1),
    "call_center_interactions": ("interaction_date", 1),
    "satisfaction_surveys": ("survey_date", 2),
    "digital_events": ("event_date", 1),
    "complaints": ("creation_date", 1),
    "campaign_sends": ("send_date", 1),
}
"""The event timestamp of each fact table and how many days after ``process_date`` it may fall (UTC events,
UTC-6 business dates; survey answers arrive up to 36 hours after the interaction)."""


@dataclass(frozen=True)
class DerivedColumn:
    name: str
    data_type: str
    description: str


SILVER_EXTRAS: dict[str, tuple[DerivedColumn, ...]] = {
    "customers": (
        DerivedColumn("has_future_last_updated", "boolean", "last_updated falls after the snapshot business day"),
    ),
    "products": (
        DerivedColumn("has_future_last_updated", "boolean", "last_updated falls after the snapshot business day"),
        DerivedColumn("has_duplicate_product_number", "boolean", "another product shares the product number (UQ)"),
    ),
    "branches": (DerivedColumn("has_duplicate_branch_code", "boolean", "another branch shares the code (UQ)"),),
    "service_agents": (
        DerivedColumn("has_duplicate_employee_code", "boolean", "another agent shares the employee code (UQ)"),
    ),
    "complaints": (
        DerivedColumn(
            "has_foreign_affected_product", "boolean", "affected_product_id names another customer's product"
        ),
    ),
    "digital_events": (DerivedColumn("has_foreign_product", "boolean", "product_id names another customer's product"),),
    "transactions": (
        DerivedColumn("amount_usd_recomputed", "boolean", "amount_usd was null and was recomputed (as-of rate)"),
        DerivedColumn("transaction_local_time", "timestamp", "transaction_date in the customer's country time zone"),
    ),
}


def orphan_flag(column: ColumnSpec) -> str:
    return f"is_orphan_{column.name}"


def _column_meta(column: ColumnSpec) -> dict[str, Any]:
    meta: dict[str, Any] = {"dtype": column.dtype, "silver_type": column.silver_type, "required": not column.nullable}
    if column.canonical is not None:
        meta["canonical"] = column.canonical
    if column.references is not None:
        meta["references"] = f"{column.references[0]}.{column.references[1]}"
    if column.pii is not None:
        meta["pii"] = column.pii
    return meta


def sources_document(config: SourceConfig) -> dict[str, Any]:
    tables = []
    for spec in TABLES:
        freshness = config.freshness.for_table(spec.name)
        tables.append(
            {
                "name": spec.name,
                "description": f"Raw {spec.name} rows as delivered ({spec.layout}), contract {CONTRACT_VERSION}.",
                "meta": {
                    "external_location": (
                        "read_parquet('{{ env_var('BANK_DATA_BRONZE_DIR') }}/"
                        + spec.name
                        + "/**/*.parquet', union_by_name = true, hive_partitioning = false)"
                    ),
                    "layout": spec.layout,
                    "primary_key": list(spec.primary_key),
                    "order_column": spec.order_column,
                    "customer_column": spec.customer_column,
                    "silver_exclude": list(spec.silver_exclude),
                },
                "loaded_at_field": "_loaded_at",
                "freshness": {
                    "warn_after": {"count": freshness.warn_after_hours, "period": "hour"},
                    "error_after": {"count": freshness.error_after_hours, "period": "hour"},
                },
                "columns": [
                    {"name": column.name, "data_type": "varchar", "meta": _column_meta(column)}
                    for column in spec.columns
                ],
            }
        )
    return {
        "version": 2,
        "sources": [
            {
                "name": "bronze",
                "description": "Contract-checked raw rows from `bank-data ingest`: strings as delivered plus lineage.",
                "tables": tables,
            }
        ],
    }


def _stg_tests(spec: TableSpec, column: ColumnSpec) -> list[Any]:
    tests: list[Any] = []
    if len(spec.primary_key) == 1 and column.name == spec.primary_key[0]:
        tests.append("unique")
    if not column.nullable:
        tests.append("not_null")
    codes = canonical_codes(column)
    if codes and column.accepted is not None:
        tests.append({"accepted_values": {"arguments": {"values": list(codes)}}})
    elif column.canonical == "country":
        tests.append(
            {"accepted_values": {"arguments": {"values": list(ISO_COUNTRIES)}, "config": {"severity": "warn"}}}
        )
    event = EVENT_TIMESTAMPS.get(spec.name)
    if event is not None and column.name == event[0]:
        tests.append({"not_after_process_date": {"arguments": {"days": event[1]}}})
    return tests


def _stg_model(spec: TableSpec) -> dict[str, Any]:
    columns: list[dict[str, Any]] = []
    for column in spec.silver_columns:
        entry: dict[str, Any] = {"name": column.name, "data_type": column.silver_type}
        tests = _stg_tests(spec, column)
        if tests:
            entry["data_tests"] = tests
        columns.append(entry)
    columns.extend({"name": name, "data_type": data_type} for name, data_type in STG_LINEAGE)
    model: dict[str, Any] = {
        "name": f"stg_{spec.name}",
        "description": (
            f"Typed, trimmed, canonical, deduplicated {spec.name} ("
            + ("incremental on process_date" if spec.layout == "daily" else "rebuilt from the snapshot")
            + ")."
        ),
        "config": {"contract": {"enforced": True}},
        "columns": columns,
    }
    if len(spec.primary_key) > 1:
        model["data_tests"] = [{"unique_combination": {"arguments": {"columns": list(spec.primary_key)}}}]
    return model


def _silver_model(spec: TableSpec) -> dict[str, Any]:
    columns: list[dict[str, Any]] = []
    for column in spec.silver_columns:
        entry: dict[str, Any] = {"name": column.name, "data_type": column.silver_type}
        if column.references is not None:
            table, field = column.references
            entry["data_tests"] = [
                {
                    "relationships": {
                        "arguments": {"to": f"ref('stg_{table}')", "field": field},
                        "config": {"severity": "warn"},
                    }
                }
            ]
        columns.append(entry)
    columns.extend({"name": name, "data_type": data_type} for name, data_type in STG_LINEAGE)
    for column in spec.foreign_keys:
        parent = column.references[0] if column.references else ""
        columns.append(
            {
                "name": orphan_flag(column),
                "data_type": "boolean",
                "description": f"{column.name} is set but has no row in {parent}",
            }
        )
    for derived in SILVER_EXTRAS.get(spec.name, ()):
        columns.append({"name": derived.name, "data_type": derived.data_type, "description": derived.description})
    return {
        "name": f"silver_{spec.name}",
        "description": f"{spec.name} with foreign-key orphan flags and derived checks (orphans kept, flagged).",
        "config": {"contract": {"enforced": True}},
        "columns": columns,
    }


def silver_document() -> dict[str, Any]:
    models: list[dict[str, Any]] = []
    for spec in TABLES:
        models.append(_stg_model(spec))
        models.append(_silver_model(spec))
    models.append(
        {
            "name": "quarantine_orphans",
            "description": "Every silver row whose foreign key has no parent: table, key, column, and value.",
            "columns": [
                {"name": "table_name", "data_type": "varchar"},
                {"name": "row_key", "data_type": "varchar"},
                {"name": "fk_column", "data_type": "varchar"},
                {"name": "fk_value", "data_type": "varchar"},
                {"name": "referenced_table", "data_type": "varchar"},
            ],
        }
    )
    return {"version": 2, "models": models}


def seed_csv() -> str:
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(["domain", "source_value", "canonical"])
    writer.writerows(seed_rows())
    return buffer.getvalue()


def _dump(document: dict[str, Any]) -> str:
    return HEADER + yaml.safe_dump(document, sort_keys=False, allow_unicode=True, width=1000)


def generated_files(project_dir: Path, config: SourceConfig) -> dict[Path, str]:
    return {
        project_dir / "models" / "sources.yml": _dump(sources_document(config)),
        project_dir / "models" / "silver" / "_silver.yml": _dump(silver_document()),
        project_dir / "seeds" / "canonical_values.csv": seed_csv(),
    }


def write_generated(project_dir: Path, config: SourceConfig) -> list[Path]:
    written = []
    for path, content in generated_files(project_dir, config).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8")
            written.append(path)
    return written


def stale_files(project_dir: Path, config: SourceConfig) -> list[Path]:
    return [
        path
        for path, content in generated_files(project_dir, config).items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
