from pathlib import Path

from bank_data.config import load_config
from bank_data.contracts.canonical import canonical_codes, canonical_value, seed_rows, snake
from bank_data.contracts.tables import TABLES, table_spec
from bank_data.settings import DBT_PROJECT_DIR, DEFAULT_CONFIG_FILE
from bank_data.transform.codegen import generated_files, silver_document, sources_document, stale_files, write_generated

CONFIG = load_config(DEFAULT_CONFIG_FILE)


def test_committed_dbt_files_match_the_table_specs() -> None:
    assert stale_files(DBT_PROJECT_DIR, CONFIG) == []


def test_write_generated_creates_then_leaves_files_alone(tmp_path: Path) -> None:
    first = write_generated(tmp_path, CONFIG)
    assert sorted(path.name for path in first) == ["_silver.yml", "canonical_values.csv", "sources.yml"]
    assert write_generated(tmp_path, CONFIG) == []
    assert stale_files(tmp_path, CONFIG) == []
    (tmp_path / "models" / "sources.yml").write_text("changed", encoding="utf-8")
    assert [path.name for path in stale_files(tmp_path, CONFIG)] == ["sources.yml"]


def test_sources_carry_layout_keys_and_freshness_per_table() -> None:
    tables = {table["name"]: table for table in sources_document(CONFIG)["sources"][0]["tables"]}
    assert set(tables) == {spec.name for spec in TABLES}
    transactions = tables["transactions"]
    assert transactions["meta"]["primary_key"] == ["transaction_id"]
    assert transactions["loaded_at_field"] == "_loaded_at"
    assert transactions["freshness"]["error_after"] == {"count": 168, "period": "hour"}
    assert tables["branches"]["freshness"]["error_after"] == {"count": 720, "period": "hour"}
    assert "digital_events" in tables["digital_events"]["meta"]["external_location"]


def test_silver_contracts_list_every_model_with_types_and_tests() -> None:
    models = {model["name"]: model for model in silver_document()["models"]}
    stg = {column["name"]: column for column in models["stg_transactions"]["columns"]}
    assert stg["amount"]["data_type"] == "decimal(15,2)"
    assert "unique" in stg["transaction_id"]["data_tests"]
    assert {"not_after_process_date": {"arguments": {"days": 1}}} in stg["transaction_date"]["data_tests"]
    silver = {column["name"]: column for column in models["silver_transactions"]["columns"]}
    assert {"is_orphan_product_id", "amount_usd_recomputed", "transaction_local_time"} <= silver.keys()
    rates = models["stg_daily_exchange_rates"]
    assert rates["data_tests"] == [
        {"unique_combination": {"arguments": {"columns": ["date", "source_currency", "target_currency"]}}}
    ]
    digital = {column["name"] for column in models["stg_digital_events"]["columns"]}
    assert "ip_address" not in digital
    assert models["quarantine_orphans"]["columns"][0]["name"] == "table_name"


def test_canonical_values_translate_spanish_and_snake_the_rest() -> None:
    assert canonical_value("product_type", "Tarjeta Crédito") == "credit_card"
    assert canonical_value("country", "México") == "MX"
    assert canonical_value("sentiment", "Muy Negativo") == "very_negative"
    assert canonical_value("snake", " In Process ") == "in_process"
    assert canonical_value("identity", " USD ") == "USD"
    assert snake("Android App") == "android_app"
    assert canonical_codes(table_spec("products").column("product_type"))[:3] == (
        "checking_account",
        "savings_account",
        "credit_card",
    )
    assert canonical_codes(table_spec("customers").column("first_name")) == ()


def test_seed_holds_only_translated_domains_and_covers_every_accepted_value() -> None:
    rows = seed_rows()
    domains = {domain for domain, _, _ in rows}
    assert "snake" not in domains
    assert ("product_type", "Seguro", "insurance") in rows
    assert ("reason_category", "Retención", "retention") in rows
    for spec in TABLES:
        for column in spec.columns:
            if column.canonical not in (None, "snake", "identity") and column.accepted:
                for value in column.accepted:
                    assert (column.canonical, value, canonical_value(str(column.canonical), value)) in rows


def test_generated_files_start_with_the_do_not_edit_header() -> None:
    for path, content in generated_files(DBT_PROJECT_DIR, CONFIG).items():
        if path.suffix == ".yml":
            assert content.startswith("# Generated by `bank-data codegen`")
