"""The version lock: each clause's current version and a digest of its language files.

A clause's content may change only together with a higher version. ``check_lock`` fails the pack when the lock
and the files disagree; ``render_lock`` writes a new lock and refuses when a changed clause kept its version,
so version numbers only ever grow.
"""

import hashlib
from collections.abc import Mapping

import yaml

from bank_agent.policy.loader.clauses import CLAUSE_PATH
from bank_agent.policy.loader.documents import PackProblems, load_yaml

LOCK_PATH = "versions.lock.yaml"
LOCK_HEADER = (
    "# Generated by `bank-agent policy lock` (make policy-lock). Do not edit by hand.\n"
    "# Each entry is a clause's current version and a SHA-256 over its language files; a changed clause must\n"
    "# carry a higher version before the lock can be rewritten.\n"
)

LockEntries = dict[str, tuple[int, str]]


def current_digests(files: Mapping[str, str]) -> dict[str, tuple[int, str]]:
    """Clause id to (version, digest) over the current files, from the front matter version line."""
    texts: dict[str, dict[str, str]] = {}
    for path, text in files.items():
        match = CLAUSE_PATH.fullmatch(path)
        if match is None or match["superseded"]:
            continue
        texts.setdefault(match["id"], {})[match["lang"]] = text.replace("\r\n", "\n")
    digests: dict[str, tuple[int, str]] = {}
    for clause_id, by_language in texts.items():
        digest = hashlib.sha256()
        for language in sorted(by_language):
            digest.update(f"{language}\n{by_language[language]}\n".encode())
        digests[clause_id] = (_version_of(by_language[sorted(by_language)[0]]), digest.hexdigest())
    return digests


def _version_of(text: str) -> int:
    for line in text.splitlines()[1:]:
        if line.startswith("version:"):
            value = line.split(":", 1)[1].strip()
            return int(value) if value.isdigit() else 0
        if line == "---":
            break
    return 0


def parse_lock(text: str | None, problems: PackProblems) -> LockEntries:
    if text is None:
        problems.add(LOCK_PATH, "the version lock is missing; run bank-agent policy lock")
        return {}
    data = load_yaml(LOCK_PATH, text, problems)
    clauses = data.get("clauses") if isinstance(data, dict) else None
    if not isinstance(clauses, dict):
        problems.add(LOCK_PATH, "the lock has a clauses mapping")
        return {}
    entries: LockEntries = {}
    for clause_id, entry in clauses.items():
        if isinstance(entry, dict) and isinstance(entry.get("version"), int) and isinstance(entry.get("digest"), str):
            entries[str(clause_id)] = (entry["version"], entry["digest"])
        else:
            problems.add(LOCK_PATH, f"entry {clause_id} needs an integer version and a digest")
    return entries


def compare(current: Mapping[str, tuple[int, str]], locked: LockEntries, problems: PackProblems) -> None:
    """Record every disagreement between the files and the lock."""
    for clause_id, (version, digest) in sorted(current.items()):
        if clause_id not in locked:
            problems.add(clause_id, "not in the version lock; run bank-agent policy lock")
            continue
        locked_version, locked_digest = locked[clause_id]
        if version < locked_version:
            problems.add(clause_id, f"version {version} is lower than the locked version {locked_version}")
        elif digest != locked_digest and version == locked_version:
            problems.add(clause_id, "the content changed without a version bump")
        elif digest != locked_digest or version != locked_version:
            problems.add(clause_id, "the version lock is stale; run bank-agent policy lock")
    for clause_id in sorted(set(locked) - set(current)):
        problems.add(clause_id, "the lock names a clause that no longer exists; run bank-agent policy lock")


def check_lock(files: Mapping[str, str], problems: PackProblems) -> None:
    compare(current_digests(files), parse_lock(files.get(LOCK_PATH), problems), problems)


def render_lock(files: Mapping[str, str]) -> str:
    """The new lock text. Raises ``ValueError`` when a clause changed or went backwards without a bump."""
    problems = PackProblems()
    current = current_digests(files)
    existing = files.get(LOCK_PATH)
    locked = parse_lock(existing, problems) if existing is not None else {}
    for clause_id, (version, digest) in current.items():
        if clause_id in locked:
            locked_version, locked_digest = locked[clause_id]
            if version < locked_version or (version == locked_version and digest != locked_digest):
                problems.add(clause_id, "bump the clause version before locking a content change")
    if problems:
        raise ValueError("; ".join(problems.items))
    body = {"clauses": {cid: {"version": v, "digest": d} for cid, (v, d) in sorted(current.items())}}
    return LOCK_HEADER + yaml.safe_dump(body, sort_keys=True, allow_unicode=True)
