/**
 * The one icon set: Phosphor, regular (outline) weight, set once by <IconContext> in the app providers. Components
 * import icons from here so the set stays auditable; add an export when a new glyph is needed.
 */
export {
  ArrowSquareOutIcon as ExternalIcon,
  ArrowClockwiseIcon as RetryIcon,
  ArrowLeftIcon as BackIcon,
  ArrowRightIcon as ForwardIcon,
  ArrowsLeftRightIcon as SwitchIcon,
  BookOpenTextIcon as BookIcon,
  CaretRightIcon as CaretRightIcon,
  ChartBarIcon as ChartIcon,
  CopyIcon as CopyIcon,
  FileTextIcon as DocumentIcon,
  FunnelSimpleIcon as FilterIcon,
  InfoIcon as InfoIcon,
  ListMagnifyingGlassIcon as TraceIcon,
  MagnifyingGlassIcon as SearchIcon,
  PaperPlaneRightIcon as SendIcon,
  PlusIcon as NewIcon,
  QuestionIcon as QuestionIcon,
  SidebarSimpleIcon as PanelIcon,
  TrayArrowDownIcon as InboxIcon,
  UserIcon as PersonIcon,
  CaretDownIcon as CaretDownIcon,
  CaretUpIcon as CaretUpIcon,
  CaretUpDownIcon as SortIcon,
  ChatCircleTextIcon as ChatIcon,
  CheckCircleIcon as CheckIcon,
  ClockIcon as ClockIcon,
  CreditCardIcon as CardIcon,
  EyeIcon as ReviewIcon,
  GearIcon as SettingsIcon,
  HeadsetIcon as HumanIcon,
  HouseIcon as HomeIcon,
  IdentificationCardIcon as IdentityIcon,
  ListIcon as MenuIcon,
  LockKeyIcon as LockIcon,
  ReceiptIcon as ReceiptIcon,
  ScalesIcon as DisputeIcon,
  ShieldCheckIcon as ShieldIcon,
  SignOutIcon as SignOutIcon,
  SquaresFourIcon as OverviewIcon,
  TrayIcon as EmptyIcon,
  WarningIcon as WarningIcon,
  WifiSlashIcon as OfflineIcon,
  WalletIcon as WalletIcon,
  XIcon as CloseIcon,
  XCircleIcon as FailedIcon,
  IconContext,
} from '@phosphor-icons/react';
export type { Icon } from '@phosphor-icons/react';
