"""Render ``docs/policy/catalog.md``: clauses, rules, bindings, the action matrix, and the credit catalog.

Pure: the caller passes the pack, the catalog entries, and the header facts (instant and commit). Everything
from ``BODY_START`` on is deterministic for a pack, so a test can check the committed file is current.
"""

from collections.abc import Iterable, Sequence

from bank_agent.domain.actions import ActionKind
from bank_agent.domain.decision import ParamValue
from bank_agent.domain.locale import Country, Language
from bank_agent.domain.money import Money
from bank_agent.domain.policy import PolicyClause
from bank_agent.policy.loader.catalog import CatalogEntry
from bank_agent.policy.pack import PolicyPack
from bank_agent.policy.rules import CONVERSATION_RULES, ELIGIBILITY_RULES
from bank_agent.policy.selection import rule_clauses

BODY_START = "## Clauses"


def _param(value: ParamValue) -> str:
    if isinstance(value, Money):
        return f"{value.amount} {value.currency.value}"
    if isinstance(value, list):
        return ", ".join(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def _params(params: dict[str, ParamValue]) -> str:
    return "; ".join(f"`{name}` = {_param(value)}" for name, value in params.items()) or "none"


def _codes(values: Iterable[str]) -> str:
    return ", ".join(f"`{value}`" for value in values) or "none"


def _table(header: Sequence[str], rows: Iterable[Sequence[str]]) -> list[str]:
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines.extend("| " + " | ".join(cell.replace("|", "/") for cell in row) + " |" for row in rows)
    return lines


def _rule_rows(current: Sequence[PolicyClause]) -> list[list[str]]:
    rows = []
    for spec in CONVERSATION_RULES.specs():
        bound = {c.metadata.clause_id for country in Country for c in rule_clauses(current, spec.rule_id, country)}
        rows.append(_rule_row(spec.rule_id, spec.version, bound, spec.params, spec.reason_codes))
    for eligibility in ELIGIBILITY_RULES.specs():
        bound = {c.metadata.clause_id for c in current if eligibility.rule_id in c.metadata.bound_rules}
        rows.append(
            _rule_row(eligibility.rule_id, eligibility.version, bound, eligibility.params, eligibility.reason_codes)
        )
    return rows


def _rule_row(
    rule_id: str, version: int, clauses: set[str], params: Iterable[str], reasons: Iterable[str]
) -> list[str]:
    return [f"`{rule_id}`", str(version), _codes(sorted(clauses)), _codes(params), _codes(reasons)]


def render_catalog(pack: PolicyPack, entries: Sequence[CatalogEntry], *, generated_at: str, commit: str) -> str:
    current = pack.list_clauses(language=Language.EN)
    catalog_version = entries[0].product.catalog_version if entries else "none"
    lines = [
        "# Policy catalog",
        "",
        f"Generated by `bank-agent policy catalog` (`make policy-catalog`) at {generated_at}, commit `{commit}`.",
        f"Inputs: policy pack `{pack.version}`, credit catalog `{catalog_version}`. Do not edit by hand.",
        "",
        "Every clause, parameter, rule, and product below is synthetic demonstration content, not a real regulation "
        "or any real bank's terms. The format and the review workflow are in "
        "[`policies/README.md`](../../policies/README.md).",
        "",
        BODY_START,
        "",
    ]
    clause_rows = [
        [
            f"`{c.metadata.clause_id}@{c.metadata.version}`",
            c.metadata.family.value,
            c.metadata.jurisdiction.value,
            _params(dict(c.metadata.params)),
            _codes(c.metadata.bound_rules),
            c.metadata.summary,
        ]
        for c in current
    ]
    lines += _table(["Clause", "Family", "Jurisdiction", "Parameters", "Bound rules", "Summary"], clause_rows)
    lines += [
        "",
        "## Rules",
        "",
        "Conversation rules run in the evaluator; ELG rules run in the eligibility service.",
        "",
    ]
    lines += _table(["Rule", "Version", "Clauses", "Parameters", "Reason codes"], _rule_rows(current))
    lines += ["", "## Bindings", "", f"Common to every state: {_codes(pack.bindings.common)}.", ""]
    binding_rows = [
        [f"`{workflow.value}`", f"`{state}`", binding.auth.value, _codes(binding.clauses)]
        for workflow, states in pack.bindings.workflows.items()
        for state, binding in states.items()
    ]
    lines += _table(["Workflow", "State", "Authentication", "Clauses"], binding_rows)
    lines += ["", "## Action matrix", ""]
    matrix_rows = []
    for action in ActionKind:
        row = pack.action_requirements(action)
        allowed = "; ".join(f"{w.value}: {', '.join(states)}" for w, states in row.allowed_states.items())
        flags = (
            str(row.requires_confirmation).lower(),
            row.required_auth_level.value,
            str(row.requires_step_up).lower(),
        )
        matrix_rows.append([f"`{action.value}`", *flags, allowed])
    lines += _table(["Action", "Confirmation", "Base level", "Step-up", "Allowed states"], matrix_rows)
    lines += ["", "## Credit catalog", ""]
    product_rows = [
        [
            f"`{e.product.product_code}`",
            e.product.product_type.value,
            e.product.jurisdiction.value,
            f"{e.product.min_amount.amount} to {e.product.max_amount.amount} {e.product.currency.value}",
            f"{e.product.min_term_months} to {e.product.max_term_months}",
            f"{e.product.min_annual_rate} to {e.product.max_annual_rate}",
            "yes" if e.product.self_service_eligibility else "no (human assessment)",
            e.display[Language.EN].name,
        ]
        for e in sorted(entries, key=lambda entry: entry.product.product_code)
    ]
    lines += _table(
        [
            "Code",
            "Type",
            "Jurisdiction",
            "Amount",
            "Term (months)",
            "Annual rate (%)",
            "Self-service eligibility",
            "Name",
        ],
        product_rows,
    )
    return "\n".join(lines) + "\n"
