"""`bank-data analysis` end to end on a warehouse built from the phase 03 fixture."""

import json
from datetime import UTC, datetime
from pathlib import Path

import pandas as pd
import pytest
from typer.testing import CliRunner

from bank_data.analysis.labeling import SAMPLE_COLUMNS
from bank_data.analysis.runner import (
    EXPECTED_OUTPUTS,
    PRELABEL_FILE,
    SAMPLE_FILE,
    AnalysisRun,
    run_analysis,
)
from bank_data.cli import app
from bank_data.errors import ConfigurationError
from bank_data_fixture import copy_parts, ingest_and_build, workspace


@pytest.fixture(scope="module")
def warehouse_db(tmp_path_factory: pytest.TempPathFactory) -> Path:
    root = tmp_path_factory.mktemp("analysis")
    space = workspace(copy_parts(root / "source", "base"), root / "warehouse")
    ingest_and_build(space)
    return space.dbt_target().warehouse_db


def _run(warehouse_db: Path, root: Path) -> AnalysisRun:
    return AnalysisRun(
        warehouse_db=warehouse_db,
        output_dir=root / "analysis",
        labeling_dir=root / "labeling",
        source="local",
        dataset_version="fixture",
        generated_at=datetime(2026, 9, 26, tzinfo=UTC),
        git_sha="abc1234",
    )


def test_analysis_on_the_fixture_writes_every_expected_file(warehouse_db: Path, tmp_path: Path) -> None:
    outcome = run_analysis(_run(warehouse_db, tmp_path))

    for name in EXPECTED_OUTPUTS:
        path = tmp_path / "analysis" / name
        assert path.is_file(), name
        assert path.stat().st_size > 0, name
    assert sorted(path.relative_to(tmp_path / "analysis").as_posix() for path in outcome.written) == sorted(
        EXPECTED_OUTPUTS
    )
    evidence = (tmp_path / "analysis" / "workflow-evidence.md").read_text(encoding="utf-8")
    assert "Generated by `make analysis` at 2026-09-26T00:00:00+00:00 from commit `abc1234`" in evidence
    assert "`local` (local directory (test fixture))" in evidence
    assert "pending human labels" in evidence
    for workflow in ("account_inquiry", "card_support", "dispute", "credit"):
        assert f"## Workflow `{workflow}`" in evidence
    scores = (tmp_path / "analysis" / "workflow-scores.md").read_text(encoding="utf-8")
    assert "## Weight sensitivity" in scores
    assert sorted(outcome.ranking) == ["account_inquiry", "card_support", "credit", "dispute"]
    document = json.loads((tmp_path / "analysis" / "analysis-results.json").read_text(encoding="utf-8"))
    assert document["meta"]["source"] == "local"
    assert len(document["results"]["scores"]["sensitivity"]["variants"]) == 12
    assert document["results"]["mapping"]["unmapped_interactions"] == 0

    sample = pd.read_csv(tmp_path / "labeling" / SAMPLE_FILE, dtype=str, keep_default_na=False)
    assert list(sample.columns) == list(SAMPLE_COLUMNS)
    assert (sample["adjudicated_resolvable"] == "").all()
    prelabels = pd.read_csv(tmp_path / "labeling" / PRELABEL_FILE, dtype=str, keep_default_na=False)
    assert set(prelabels["review_status"]) <= {"pending"}
    assert outcome.labeling_status == "written"


def test_a_rerun_keeps_human_labels_and_reads_them(warehouse_db: Path, tmp_path: Path) -> None:
    run = _run(warehouse_db, tmp_path)
    run_analysis(run)
    path = tmp_path / "labeling" / SAMPLE_FILE
    sample = pd.read_csv(path, dtype=str, keep_default_na=False)
    if sample.empty:
        pytest.skip("the fixture has no transcript with customer text")
    sample.loc[0, ["adjudicated_resolvable", "adjudicated_matches_workflow"]] = ["yes", "yes"]
    sample.to_csv(path, index=False)

    outcome = run_analysis(run)

    assert outcome.labeling_status == "kept"
    kept = pd.read_csv(path, dtype=str, keep_default_na=False)
    assert kept.loc[0, "adjudicated_resolvable"] == "yes"
    document = json.loads((tmp_path / "analysis" / "analysis-results.json").read_text(encoding="utf-8"))
    labels = document["results"]["labels"]["workflows"][sample.loc[0, "workflow_stratum"]]
    assert labels["adjudicated"] == 1
    assert labels["status"].startswith("insufficient matching labels")


def test_analysis_without_a_warehouse_is_a_configuration_error(tmp_path: Path) -> None:
    with pytest.raises(ConfigurationError, match="no built warehouse"):
        run_analysis(_run(tmp_path / "missing.duckdb", tmp_path))


def test_cli_writes_reports_next_to_a_non_organizer_warehouse(
    warehouse_db: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    source_dir = warehouse_db.parent.parent / "source"
    monkeypatch.setenv("BANK_DATA_WAREHOUSE_DIR", str(warehouse_db.parent))
    result = CliRunner().invoke(
        app,
        [
            "analysis",
            "--source",
            "local",
            "--local-dir",
            str(source_dir),
            "--output-dir",
            str(tmp_path / "out"),
            "--labeling-dir",
            str(tmp_path / "labels"),
        ],
    )
    assert result.exit_code == 0, result.output
    assert "order: " in result.output
    assert (tmp_path / "out" / "workflow-evidence.md").is_file()
    assert (tmp_path / "labels" / SAMPLE_FILE).is_file()


def test_cli_reports_a_missing_warehouse_with_the_configuration_exit_code(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("BANK_DATA_WAREHOUSE_DIR", str(tmp_path / "empty"))
    result = CliRunner().invoke(app, ["analysis", "--source", "local", "--local-dir", str(tmp_path)])
    assert result.exit_code == 2
