"""The provenance README of the committed sample, generated with the files (CLAUDE.md rule 5).

It carries no generation timestamp or git sha on purpose: ``make data-sample`` must leave ``git status`` clean
when the dataset version and seed are unchanged, so every line is a function of those inputs.
"""

import hashlib
from collections.abc import Mapping, Sequence
from dataclasses import dataclass

from bank_data.contracts.tables import TABLES, PiiKind
from bank_data.sample.extract import COVERAGE_TARGETS, FACT_CAPS, PREVIEW_DIR, Row, SampleSettings

REQUIRED_SECTIONS = (
    "## Source",
    "## Dataset version",
    "## Extraction",
    "## Row counts",
    "## Column treatments",
    "## Data-use terms",
)
_TREATMENTS: dict[PiiKind, str] = {
    "document_number": "every digit and letter replaced in place (same length and pattern)",
    "first_name": "invented name with the same number of parts",
    "last_name": "invented name with the same number of parts",
    "date_of_birth": "shifted by 1 to 365 days",
    "email": "rebuilt from the pseudonymized names at example.com",
    "phone": "country prefix and grouping kept, every other digit replaced",
    "address": "invented street, number, and neighborhood",
    "product_number": "digits replaced in place (letter prefixes such as POL- kept)",
    "ip_address": "RFC 5737 documentation address (192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24)",
}
_EXAMPLE_ROWS = 3
_CELL_WIDTH = 32


@dataclass(frozen=True)
class DatasetVersion:
    label: str
    snapshot_date: str
    snapshot_etags: tuple[tuple[str, str], ...]
    """``(object key, etag)`` of each root snapshot file."""
    partition_digests: tuple[tuple[str, int, str], ...]
    """``(table, object count, sha256 of the sorted key:etag lines)`` of each daily table."""


def partition_digest(pairs: Sequence[tuple[str, str]]) -> str:
    lines = "\n".join(f"{key}:{etag}" for key, etag in sorted(pairs))
    return hashlib.sha256(lines.encode("utf-8")).hexdigest()[:16]


def _cell(value: str) -> str:
    """A table cell: whitespace collapsed, shortened, and shown as code (so emails are not read as links)."""
    flat = " ".join(value.split()).replace("`", "'")
    if not flat:
        return ""
    shown = flat if len(flat) <= _CELL_WIDTH else flat[: _CELL_WIDTH - 3] + "..."
    return "`" + shown.replace("|", "\\|") + "`"


def render_readme(
    tables: Mapping[str, list[Row]],
    preview_rows: int,
    version: DatasetVersion,
    settings: SampleSettings,
    customers: int,
    coverage: Mapping[str, bool],
) -> str:
    sample_total = sum(len(rows) for rows in tables.values())
    preview_counts = {name: min(len(rows), preview_rows) for name, rows in tables.items()}
    preview_total = sum(preview_counts.values())
    lines = [
        "# Committed organizer data sample",
        "",
        "**Organizer-provided synthetic data, subject to the organizer's data-use terms.** This directory is the "
        "only organizer data in the repository (CLAUDE.md rule 5). It is generated by `make data-sample`; do not "
        "edit it by hand. The full dataset lives under the gitignored `data/` directory and never enters git.",
        "",
        "## Source",
        "",
        "- The Factored AI & Data Hackathon 2026 organizer dataset (LATAM Bank, fully synthetic, generated for the "
        "event), read from the organizer S3 bucket (`data/` prefix) by `bank-data ingest --source s3`.",
        "- Rows come from the contract-checked bronze layer (raw values as delivered, deduplicated like silver).",
        "- The files keep the bucket layout (`<table>.csv` and "
        "`<table>/year=YYYY/month=MM/day=DD/<table>_YYYYMMDD.csv`), so `make pipeline` (source `sample`) "
        "builds bronze, silver, and gold from this directory alone, with no network and no credentials. "
        "`preview/` holds the first rows of each table for reading and is never ingested.",
        "",
        "## Dataset version",
        "",
        f"- Delivery: `{version.label}`; snapshot date of the root files: {version.snapshot_date}.",
        "- Root snapshot files and their manifest etags:",
        "",
        "| Object | Etag |",
        "|---|---|",
        *(f"| `{key}` | `{etag}` |" for key, etag in version.snapshot_etags),
        "",
        "- Daily tables: object count and a digest (first 16 hex characters of the sha256 of the sorted "
        "`key:etag` lines from the manifest):",
        "",
        "| Table | Objects | Digest |",
        "|---|---|---|",
        *(f"| {table} | {count} | `{digest}` |" for table, count, digest in version.partition_digests),
        "",
        "## Extraction",
        "",
        "```bash",
        "make data-sample    # runs: uv run bank-data sample (reads data/warehouse, the s3 source)",
        "```",
        "",
        f"- Seed: `{settings.seed}`. Customers are ranked by `sha256(seed || ':' || customer_id)` over the "
        "deduplicated bronze customers.",
        f"- The first {settings.min_customers} ranked customers are taken; after that, a customer is taken only when "
        f"it covers a case the sample still lacks or adds complaints until there are {settings.min_complaints}, and "
        f"the walk stops once every case is covered ({customers} customers were taken).",
        f"- Fact rows: the last {settings.window_days} days of the dataset (process_date), capped per customer: "
        + ", ".join(f"{table} {cap}" for table, cap in FACT_CAPS.items())
        + "; call_transcripts follow the selected interactions. Within a cap, the first row of each rare "
        "type and status comes first, then rows in hash order.",
        "- Referential closure: products of the selected customers; transcripts, surveys, and complaints only when "
        "the interaction or product they reference is selected; branches, service agents, marketing campaigns, "
        "and exchange-rate rows only when a selected row references them (rates: the USD rate of each business "
        "date whose transaction lacks amount_usd).",
        "- Query outline (DuckDB over bronze Parquet): deduplicate each table with `row_number() over (partition by "
        "<primary key> order by <order column> desc, _etag desc, _source_key desc, _source_row desc)`, select the "
        "ranked customers' rows, apply the caps in Python, then pseudonymize.",
        "",
        "## Row counts",
        "",
        "| Table | Sample rows | Preview rows |",
        "|---|---|---|",
        *(
            f"| {spec.name} | {len(tables.get(spec.name, []))} | {preview_counts.get(spec.name, 0)} |"
            for spec in TABLES
        ),
        f"| **Total** | **{sample_total}** | **{preview_total}** |",
        "",
        f"Rows committed, sample plus preview: {sample_total + preview_total} of the {settings.row_limit:,} allowed. "
        "No table is copied whole. `scripts/checks/check_data_sample.py` (part of `make check`) recounts every file.",
        "",
        "Coverage of the four workflows (every case must be present, or `make data-sample` fails):",
        "",
        "| Case | Present |",
        "|---|---|",
        *(f"| {target} | {'yes' if coverage.get(target) else 'no'} |" for target in COVERAGE_TARGETS),
        "",
        "## Column treatments",
        "",
        "Direct identifiers are replaced by deterministic pseudonyms derived from the table, column, and row key "
        "with no secret, and never equal to any original value of the same column in the sample.",
        "",
        "| Table | Column | Treatment |",
        "|---|---|---|",
        *(
            f"| {spec.name} | {column.name} | {_TREATMENTS[column.pii]} |"
            for spec in TABLES
            for column in spec.columns
            if column.pii is not None
        ),
        "",
        "Every other column is kept as delivered. Free text (transcripts, complaint descriptions and resolutions, "
        "survey comments) was profiled in phase 03: it is templated (for example `{monto} {moneda}`) and holds no "
        "names or identifiers. Branch contact details are the bank's, not a person's. The sample never contains "
        "credentials, `.env` values, or anything from the organizer data dictionary PDF.",
        "",
        "## Tables at a glance",
        "",
        f"The first {_EXAMPLE_ROWS} rows of each table (cells longer than {_CELL_WIDTH} characters are shortened "
        f"here; `{PREVIEW_DIR}/<table>.csv` has the first {preview_rows} rows in full).",
        "",
    ]
    for spec in TABLES:
        rows = tables.get(spec.name, [])[:_EXAMPLE_ROWS]
        lines += [
            f"### {spec.name}",
            "",
            f"{spec.layout.capitalize()} table, primary key `{', '.join(spec.primary_key)}`, "
            f"{len(spec.columns)} columns.",
            "",
            "| " + " | ".join(spec.column_names) + " |",
            "|" + "---|" * len(spec.column_names),
            *("| " + " | ".join(_cell(row.get(name, "")) for name in spec.column_names) + " |" for row in rows),
            "",
        ]
    lines += [
        "## Data-use terms",
        "",
        "This is organizer-provided synthetic data and remains subject to the organizer's data-use terms. They were "
        "checked before the repository was made public: on 2026-09-30 the human confirmed that no restriction on "
        "redistributing this sample is known, and the reasoning is recorded in `docs/data/data-use.md`. If the "
        "organizer's terms forbid redistribution, the team asks the human, and history is never rewritten to remove "
        "the sample without the human's explicit instruction.",
        "",
    ]
    return "\n".join(lines)
