// Generates the TypeScript types of the API from the committed OpenAPI document (contracts/openapi.json).
// `make openapi` writes src/shared/api/generated/schema.d.ts with it, and api-types.test.ts fails when the
// committed file differs, so the backend contract and the frontend types never drift apart.
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import openapiTS, { astToString } from 'openapi-typescript';

export const specPath = fileURLToPath(new URL('../../../contracts/openapi.json', import.meta.url));
export const typesPath = fileURLToPath(
  new URL('../src/shared/api/generated/schema.d.ts', import.meta.url),
);

const header = [
  '/**',
  ' * Generated by `make openapi` from contracts/openapi.json with openapi-typescript.',
  ' * Do not edit by hand; change the backend and regenerate.',
  ' */',
  '',
].join('\n');

export async function generateApiTypes(path: string = specPath): Promise<string> {
  const spec: unknown = JSON.parse(await readFile(path, 'utf8'));
  const ast = await openapiTS(spec as Parameters<typeof openapiTS>[0], { alphabetize: true });
  return `${header}${astToString(ast)}`;
}
