#!/usr/bin/env python3
"""Create a local ``.env`` from ``.env.example`` with freshly generated development secrets.

Usage:
    make env
    python3 scripts/make_env.py [--example .env.example] [--target .env]

It never overwrites an existing target. Every ``dev-only-`` placeholder in the example is replaced with a new random
value (``secrets.token_urlsafe(48)``), written straight to the file with owner-only permissions; no value is ever
printed. `cp .env.example .env` also works for development; this is the stronger option. If the compose PostgreSQL
volume was already initialized with other passwords, keep that `.env` or recreate the volume (`make down`, then
remove the volume).
"""

from __future__ import annotations

import argparse
import os
import re
import secrets
import sys
from pathlib import Path

PLACEHOLDER = re.compile(r"^([A-Z][A-Z0-9_]*)=dev-only-\S*(.*)$")
GENERATED_NOTE = "  # generated by make env for local development; never reuse it elsewhere"


def render(example: str) -> tuple[str, int]:
    """The example with every dev-only placeholder replaced, and how many were replaced."""
    lines, replaced = [], 0
    for line in example.splitlines():
        match = PLACEHOLDER.match(line)
        if match:
            lines.append(f"{match.group(1)}={secrets.token_urlsafe(48)}{GENERATED_NOTE}")
            replaced += 1
        else:
            lines.append(line)
    return "\n".join(lines) + "\n", replaced


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else None)
    parser.add_argument("--example", type=Path, default=Path(".env.example"))
    parser.add_argument("--target", type=Path, default=Path(".env"))
    arguments = parser.parse_args(argv)
    if arguments.target.exists():
        print(f"make-env: {arguments.target} already exists; left unchanged")
        return 0
    if not arguments.example.is_file():
        print(f"make-env: example file not found: {arguments.example}", file=sys.stderr)
        return 2
    text, replaced = render(arguments.example.read_text(encoding="utf-8"))
    descriptor = os.open(arguments.target, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
        handle.write(text)
    print(f"make-env: wrote {arguments.target} with {replaced} freshly generated development secret(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
