"""Tests for scripts/make_env.py. Temporary files only; the real .env is never touched."""

import importlib.util
import stat
import sys
from pathlib import Path
from types import ModuleType

import pytest

SCRIPT = Path(__file__).resolve().parents[2] / "make_env.py"
EXAMPLE = Path(__file__).resolve().parents[3] / ".env.example"


def _load() -> ModuleType:
    spec = importlib.util.spec_from_file_location("make_env", SCRIPT)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules["make_env"] = module
    spec.loader.exec_module(module)
    return module


make_env = _load()


def test_writes_fresh_secrets_owner_only_and_prints_no_value(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    first, second = tmp_path / "first.env", tmp_path / "second.env"
    assert make_env.main(["--example", str(EXAMPLE), "--target", str(first)]) == 0
    assert make_env.main(["--example", str(EXAMPLE), "--target", str(second)]) == 0
    output = capsys.readouterr().out
    text, other = first.read_text(encoding="utf-8"), second.read_text(encoding="utf-8")
    assert "dev-only-" not in text.replace("dev-only- are", "")
    assert "with 4 freshly generated development secret(s)" in output
    assert stat.S_IMODE(first.stat().st_mode) == 0o600
    secret_lines = [line for line in text.splitlines() if line.startswith(("SESSION_SECRET=", "CSRF_SECRET="))]
    assert len(secret_lines) == 2
    for line in secret_lines:
        value = line.split("=", 1)[1].split()[0]
        assert len(value) >= 48
        assert value not in output
        assert value not in other
    kept = [line for line in EXAMPLE.read_text(encoding="utf-8").splitlines() if "dev-only-not" not in line]
    assert [line for line in text.splitlines() if "generated by make env" not in line] == kept


def test_never_overwrites_an_existing_file(tmp_path: Path) -> None:
    target = tmp_path / ".env"
    target.write_text("KEEP=1\n", encoding="utf-8")
    assert make_env.main(["--example", str(EXAMPLE), "--target", str(target)]) == 0
    assert target.read_text(encoding="utf-8") == "KEEP=1\n"


def test_a_missing_example_is_an_input_error(tmp_path: Path) -> None:
    assert make_env.main(["--example", str(tmp_path / "absent"), "--target", str(tmp_path / ".env")]) == 2
