"""Turn dbt's ``manifest.json`` into a Mermaid flowchart of the lineage (``docs/data/lineage.md``)."""

import json
import re
from collections.abc import Mapping
from datetime import datetime
from pathlib import Path
from typing import Any

_LAYERS = (
    ("bronze", "Bronze (sources)"),
    ("seeds", "Seeds"),
    ("silver", "Silver"),
    ("serving", "Gold serving (Parquet)"),
    ("ml", "Gold ML inputs"),
    ("marts", "Gold marts"),
)


def _node_id(unique_id: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", unique_id.split(".", 2)[-1])


def _layer(node: Mapping[str, Any]) -> str | None:
    resource = node.get("resource_type")
    if resource == "source":
        return "bronze"
    if resource == "seed":
        return "seeds"
    if resource != "model":
        return None
    path = str(node.get("original_file_path", ""))
    for layer in ("serving", "ml", "marts"):
        if f"/gold/{layer}/" in path:
            return layer
    return "silver"


def lineage_graph(manifest: Mapping[str, Any]) -> tuple[dict[str, list[tuple[str, str]]], list[tuple[str, str]]]:
    """Nodes per layer (``(id, label)``) and edges (parent id, child id), sorted for stable output."""
    nodes: dict[str, list[tuple[str, str]]] = {layer: [] for layer, _ in _LAYERS}
    known: set[str] = set()
    for collection in ("sources", "nodes"):
        for unique_id, node in manifest.get(collection, {}).items():
            layer = _layer(node)
            if layer is None:
                continue
            label = f"{node.get('source_name')}.{node.get('name')}" if layer == "bronze" else str(node.get("name"))
            nodes[layer].append((_node_id(unique_id), label))
            known.add(unique_id)
    edges: set[tuple[str, str]] = set()
    for unique_id, node in manifest.get("nodes", {}).items():
        if unique_id not in known:
            continue
        for parent in node.get("depends_on", {}).get("nodes", []):
            if parent in known:
                edges.add((_node_id(parent), _node_id(unique_id)))
    return {layer: sorted(items) for layer, items in nodes.items()}, sorted(edges)


def render_lineage(manifest: Mapping[str, Any], *, generated_at: datetime, git_sha: str, source_label: str) -> str:
    nodes, edges = lineage_graph(manifest)
    lines = [
        "# Data lineage",
        "",
        f"Generated by `make lineage` at {generated_at.isoformat(timespec='seconds')} from commit `{git_sha}` "
        f"(dbt manifest of the `{source_label}` warehouse). Do not edit by hand; `dbt docs generate` writes the "
        "full catalog under the warehouse `dbt/full/dbt_target/` directory.",
        "",
        f"{sum(len(items) for items in nodes.values())} nodes and {len(edges)} dependencies. Bronze tables are "
        "the dbt sources over the Parquet written by `bank-data ingest`; `stg_` models type and deduplicate, "
        "`silver_` views flag orphans and derive checks, and gold serves the demo, the ML phases, and analytics.",
        "",
        "```mermaid",
        "flowchart LR",
    ]
    for layer, title in _LAYERS:
        if not nodes[layer]:
            continue
        lines.append(f'    subgraph {layer}["{title}"]')
        lines.extend(f'        {node_id}["{label}"]' for node_id, label in nodes[layer])
        lines.append("    end")
    lines.extend(f"    {parent} --> {child}" for parent, child in edges)
    lines += ["```", ""]
    return "\n".join(lines)


def load_manifest(path: Path) -> dict[str, Any]:
    document: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
    return document
