"""Markdown rendering of the evidence (``workflow-evidence.md``) and the scores (``workflow-scores.md``)."""

from typing import Any

from bank_data.analysis.config import CRITERIA, SCENARIOS, WORKFLOWS
from bank_data.analysis.evidence import FLAT_PATTERN_RATIO, SEGMENT_DIMENSIONS, WEEKDAYS
from bank_data.analysis.labeling import PENDING

Result = dict[str, Any]
NOT_DEFINED = "not defined"


def pct(value: float | None, digits: int = 1) -> str:
    return NOT_DEFINED if value is None else f"{100.0 * value:.{digits}f}%"


def num(value: float | int | None, digits: int = 0) -> str:
    if value is None:
        return NOT_DEFINED
    return f"{value:,.{digits}f}"


def money(value: float | str | None, currency: str) -> str:
    if isinstance(value, str):
        return value
    if value is None:
        return NOT_DEFINED
    return f"{value:,.2f} {currency}" if abs(value) < 1_000 else f"{value:,.0f} {currency}"


def interval_pct(item: Result) -> str:
    if item.get("estimate") is None:
        return NOT_DEFINED
    return f"{pct(item['estimate'])} ({pct(item['low'])} to {pct(item['high'])})"


def interval_num(item: Result, digits: int = 1) -> str:
    if item.get("estimate") is None:
        return NOT_DEFINED
    return f"{num(item['estimate'], digits)} ({num(item['low'], digits)} to {num(item['high'], digits)})"


def _table(header: list[str], rows: list[list[str]]) -> list[str]:
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return lines


def _mix(rows: list[list[Any]], limit: int = 6) -> str:
    return ", ".join(f"{key} {pct(share)}" for key, _count, share in rows[:limit]) or NOT_DEFINED


def header(meta: Result, title: str) -> list[str]:
    return [
        f"# {title}",
        "",
        f"Generated by `make analysis` at {meta['generated_at']} from commit `{meta['git_sha']}`. "
        f"Source: `{meta['source']}` ({meta['source_description']}); delivery `{meta['dataset_version']}`; "
        f"contacts from {meta['first_day']} to {meta['last_day']}. Pre-registration version "
        f"{meta['preregistration_version']}. Do not edit by hand.",
        "",
    ]


# --------------------------------------------------------------------------------------------- evidence


def render_evidence(results: Result, meta: Result) -> str:
    lines = header(meta, "Workflow evidence")
    currency = results["costs"]["currency"]
    lines += [
        "Every figure here is an offline measurement of the historical organizer data, except the cost figures, "
        "which are projections from stated assumptions (`data_platform/analysis/cost_assumptions.yaml`, all "
        "marked `assumption: true`). Intervals are bootstrap 95% intervals "
        f"({results_meta_resamples(meta)} resamples). The method is pre-registered in "
        "[`workflow-scoring-preregistration.md`](workflow-scoring-preregistration.md); the scores are in "
        "[`workflow-scores.md`](workflow-scores.md).",
        "",
        "## Summary per workflow",
        "",
    ]
    rows = []
    volume = results["volume"]["primary"]
    for workflow in WORKFLOWS:
        outcome = results["outcomes"][workflow]
        cost = results["costs"]["workflows"][workflow]["scenarios"]["1"]
        rows.append(
            [
                f"`{workflow}`",
                num(volume[workflow]["interactions"]),
                num(volume[workflow]["complaints"]),
                pct(volume[workflow]["contact_share"]),
                pct(outcome["first_contact_resolution"]["estimate"]),
                pct(outcome["escalation"]["estimate"]),
                num(outcome["handle_time_seconds"]["estimate"]),
                pct(outcome["csat_low_share"]["estimate"]),
                pct(results["automatable"][workflow]["proxy"]["estimate"]),
                results["automatable"][workflow]["label_status"],
                money(cost["cost_per_contact"], currency),
            ]
        )
    lines += _table(
        [
            "Workflow",
            "Interactions",
            "Complaints",
            "Share of all contacts",
            "First contact resolution",
            "Escalation",
            "Handle time (s)",
            "Low CSAT (1 or 2)",
            "Automatable, proxy",
            "Automatable, human labels",
            "Cost per contact (projected)",
        ],
        rows,
    )
    other = volume["other"]
    lines += [
        "",
        f"`other` (technical support, retention, and service, app, and branch complaints) holds "
        f"{num(other['interactions'])} interactions and {num(other['complaints'])} complaints "
        f"({pct(other['contact_share'])} of all contacts).",
        "",
    ]
    lines += _mapping_section(results)
    lines += _volume_section(results)
    for workflow in WORKFLOWS:
        lines += _workflow_section(results, workflow)
    lines += _patterns_section(results)
    lines += _lag_section(results)
    lines += _automatable_section(results)
    lines += _cost_section(results)
    lines += _segments_section(results)
    lines += _support_section(results)
    lines += _stop_section(results)
    lines += _evidence_limitations()
    return "\n".join(lines).rstrip() + "\n"


def results_meta_resamples(meta: Result) -> str:
    return num(meta.get("bootstrap_resamples"))


def _mapping_section(results: Result) -> list[str]:
    mapping = results["mapping"]
    lines = [
        "## Reason mapping",
        "",
        "From [`data_platform/mappings/workflow_mapping.csv`](../../data_platform/mappings/workflow_mapping.csv). "
        "The contact reasons are coarse (six values), so three of the four interaction mappings are assumptions; "
        "the strict and alternative columns are the pre-registered sensitivity scenarios.",
        "",
    ]
    lines += _table(
        ["Contact reason", "Interactions", "Primary", "Strict", "Alternative"],
        [
            [
                row["contact_reason"],
                num(row["interactions"]),
                str(row["workflow"]),
                str(row["strict"]),
                str(row["alternative"]),
            ]
            for row in mapping["contact_reasons"]
        ],
    )
    lines += [""]
    lines += _table(
        ["Complaint category", "Subcategory", "Complaints", "Workflow", "Sub-intent"],
        [
            [
                row["category"],
                row["subcategory"] or "(null)",
                num(row["complaints"]),
                str(row["workflow"]),
                row["sub_intent"] or "",
            ]
            for row in mapping["complaint_categories"]
        ],
    )
    unmapped = ", ".join(mapping["unmapped_values"]) or "none"
    lines += [
        "",
        f"Unmapped volume: {num(mapping['unmapped_interactions'])} interactions "
        f"({pct(mapping['unmapped_interaction_share'], 2)}) and {num(mapping['unmapped_complaints'])} complaints "
        f"({pct(mapping['unmapped_complaint_share'], 2)}); unmapped values: {unmapped}. Interactions whose "
        f"`reason_category` row disagrees with their `contact_reason` row: "
        f"{num(mapping['reason_category_conflicts'])}.",
        "",
    ]
    return lines


def _contacts(item: Result) -> int:
    return int(item["interactions"]) + int(item["complaints"])


def _volume_section(results: Result) -> list[str]:
    lines = [
        "## Volume and trend",
        "",
        "Share of all contacts (interactions plus complaints) per mapping scenario:",
        "",
    ]
    rows = []
    for workflow in (*WORKFLOWS, "other"):
        rows.append(
            [f"`{workflow}`"]
            + [
                f"{pct(results['volume'][scenario][workflow]['contact_share'])} "
                f"({num(_contacts(results['volume'][scenario][workflow]))})"
                for scenario in SCENARIOS
            ]
        )
    lines += _table(["Workflow", "Primary", "Strict", "Alternative"], rows)
    trend = results["trend"]
    first, last = trend["first_window"], trend["last_window"]
    lines += ["", "![Contacts per workflow and month](figures/monthly-volume.png)", ""]
    if first and last:
        lines += [
            f"Trend: contacts in the first 12 full months ({first[0]} to {first[1]}) against the last 12 "
            f"({last[0]} to {last[1]}).",
            "",
        ]
        lines += _table(
            ["Workflow", "First 12 months", "Last 12 months", "Change"],
            [
                [
                    f"`{workflow}`",
                    num(trend["workflows"][workflow]["first_12_full_months"]),
                    num(trend["workflows"][workflow]["last_12_full_months"]),
                    pct(trend["workflows"][workflow]["change"]),
                ]
                for workflow in WORKFLOWS
            ],
        )
        lines += [""]
    return lines


def _workflow_section(results: Result, workflow: str) -> list[str]:
    outcome = results["outcomes"][workflow]
    patterns = results["patterns"]["workflows"][workflow]
    currency = results["costs"]["currency"]
    cost = results["costs"]["workflows"][workflow]
    lines = [f"## Workflow `{workflow}`", ""]
    rows = [
        ["Interactions", num(outcome["interactions"]), ""],
        [
            "First contact resolution",
            interval_pct(outcome["first_contact_resolution"]),
            num(outcome["first_contact_resolution"]["n"]),
        ],
        ["Escalation rate", interval_pct(outcome["escalation"]), num(outcome["escalation"]["n"])],
        ["Needs follow-up", interval_pct(outcome["requires_followup"]), num(outcome["requires_followup"]["n"])],
        [
            "Handle time, seconds",
            interval_num(outcome["handle_time_seconds"]),
            num(outcome["handle_time_seconds"]["n"]),
        ],
        ["Wait time, seconds", interval_num(outcome["wait_time_seconds"]), num(outcome["wait_time_seconds"]["n"])],
        ["CSAT mean (observed scale 1 to 4)", interval_num(outcome["csat_mean"], 2), num(outcome["csat_mean"]["n"])],
        ["CSAT share 1 or 2", interval_pct(outcome["csat_low_share"]), num(outcome["csat_low_share"]["n"])],
        [
            "NPS (promoters minus detractors; no score above 7 exists)",
            num(outcome["nps"]["score"], 1),
            num(outcome["nps"]["n"]),
        ],
        ["CES mean", interval_num(outcome["ces_mean"], 2), num(outcome["ces_mean"]["n"])],
        [
            "Automatable share, proxy (resolved, not escalated, no follow-up)",
            interval_pct(results["automatable"][workflow]["proxy"]),
            num(results["automatable"][workflow]["proxy"]["n"]),
        ],
        ["Automatable share, human labels", results["automatable"][workflow]["label_status"], ""],
    ]
    lines += _table(["Metric", "Value (95% interval)", "n"], rows)
    lines += [
        "",
        f"Channel mix: {_mix(outcome['channel_mix'])}. Country mix: {_mix(outcome['country_mix'])}.",
        "",
    ]
    if outcome["complaints"]:
        lines += _table(
            ["Complaint metric", "Value (95% interval)"],
            [
                ["Complaints", num(outcome["complaints"])],
                ["SLA breach rate", interval_pct(outcome["sla_breach"])],
                ["Resolution days (resolved complaints)", interval_num(outcome["resolution_days"])],
                ["Repeat complainer rate", interval_pct(outcome["repeat_complainer"])],
                ["Share with compensation granted", pct(outcome["compensation_granted_share"])],
                ["Share with a claimed amount", pct(outcome["claimed_amount_present_share"])],
                ["Case type mix", _mix(outcome["case_type_mix"])],
                ["Status mix", _mix(outcome["status_mix"])],
                ["Reception channel mix", _mix(outcome["complaint_channel_mix"])],
                ["Country mix", _mix(outcome["complaint_country_mix"])],
            ],
        )
        lines += [""]
    else:
        lines += [
            "No complaint category maps to this workflow, so SLA, resolution days, repeat complainers, and "
            "compensation are not defined for it.",
            "",
        ]
    lines += [
        f"Demand pattern: {_hour_text(patterns)}; {_weekday_text(patterns)}; mean {num(patterns['daily_mean'], 1)} "
        f"contacts a day over {num(patterns['days'])} days, {num(patterns['spikes'])} spike days (robust z above the "
        "pre-registered threshold).",
        "",
        "Cost (projected from assumptions): "
        f"{money(cost['scenarios']['1']['cost_per_contact'], currency)} per contact, "
        f"{money(cost['scenarios']['1']['cost_per_resolved_contact'], currency)} per resolved contact, "
        f"{money(cost['scenarios']['1']['annual_handle_cost'], currency)} of handle cost in the last 365 days.",
        "",
    ]
    return lines


def _hour_text(patterns: Result) -> str:
    ratio = patterns["hour_peak_to_trough"]
    hours = patterns["hour_of_day"]
    if ratio is None or not any(hours):
        return "hour of day not defined"
    peak = max(range(24), key=lambda hour: hours[hour])
    if ratio < FLAT_PATTERN_RATIO:
        return f"flat across the local hours of the day (peak to trough {num(ratio, 2)}, no intraday peak)"
    return f"peak local hour {peak} (peak to trough {num(ratio, 2)})"


def _weekday_text(patterns: Result) -> str:
    ratio = patterns["weekday_peak_to_trough"]
    days = patterns["weekday"]
    if ratio is None or not any(days):
        return "day of week not defined"
    peak, trough = max(range(7), key=lambda day: days[day]), min(range(7), key=lambda day: days[day])
    weekend = (days[5] + days[6]) / 2
    weekday = sum(days[:5]) / 5
    return (
        f"busiest weekday {WEEKDAYS[peak]}, quietest {WEEKDAYS[trough]} (peak to trough {num(ratio, 2)}; a weekend day "
        f"carries {pct(weekend / weekday if weekday else None)} of a weekday's volume)"
    )


def _patterns_section(results: Result) -> list[str]:
    lines = [
        "## Demand patterns",
        "",
        "Hours and weekdays are local to the customer's country (fixed offsets: Mexico UTC-6, Colombia UTC-5, "
        "Argentina UTC-3), from UTC timestamps. The hour-of-day curves are flat in every workflow (a generator "
        "property: no intraday staffing signal exists in this data); the weekly pattern is real, with weekend days "
        "at about half a weekday's volume.",
        "",
        "![Interactions by local hour of day](figures/hour-of-day.png)",
        "",
        "![Interactions by local day of week](figures/day-of-week.png)",
        "",
        "Spike days: daily contacts (interactions plus complaints) above the trailing 28-day median by more "
        "than the pre-registered robust z-score.",
        "",
    ]
    rows = []
    for workflow in WORKFLOWS:
        patterns = results["patterns"]["workflows"][workflow]
        top = "; ".join(
            f"{spike['day']} ({num(spike['volume'])} against {num(spike['baseline'], 0)}, "
            f"z {num(spike['robust_z'], 1)})"
            for spike in patterns["top_spikes"]
        )
        rows.append([f"`{workflow}`", num(patterns["days"]), num(patterns["spikes"]), top or "none"])
    lines += _table(["Workflow", "Days", "Spike days", "Largest spikes"], rows)
    lines += [""]
    return lines


def _lag_section(results: Result) -> list[str]:
    lag = results["lag"]
    error, baseline = lag["error"], lag["baseline"]
    lines = [
        "## Digital errors followed by a contact",
        "",
        f"For digital events of identified customers: the share followed by a contact-center interaction of the "
        f"same customer within {lag['window_hours']} hours, for `error` events against a deterministic 5% hash "
        "sample of all other events. **This is an association, not a causal effect**: customers who use digital "
        "channels more also call more, and the synthetic generator may not link the two at all.",
        "",
    ]
    lines += _table(
        ["Events", "Count", "Contact within the window (95% interval)"],
        [
            ["Error events", num(error["events"]), interval_pct(error["contact_within_window"])],
            ["Other events (5% sample)", num(baseline["events"]), interval_pct(baseline["contact_within_window"])],
        ],
    )
    lines += [
        "",
        f"Rate ratio (error over other): {num(lag['rate_ratio'], 2)}. Workflow of the contact after an error: "
        f"{_mix(error['contact_workflows'])}.",
        "",
        "![Contact after a digital event](figures/error-contact-lag.png)",
        "",
    ]
    lines += _table(
        ["Page of the error", "Error events", "Contact within the window"],
        [[str(page), num(count), pct(share, 2)] for page, count, share in lag["error_pages"][:10]],
    )
    lines += [""]
    return lines


def _automatable_section(results: Result) -> list[str]:
    transcripts = results["transcripts"]
    facts = transcripts["facts"]
    lines = [
        "## Automatable share and the labeling task",
        "",
        "The automatable share is a human labeling task ([`labeling-protocol.md`](labeling-protocol.md)). "
        "Until at least the pre-registered number of adjudicated items per workflow match that workflow, every "
        "score uses the structured proxy (resolved at first contact, not escalated, no follow-up), labeled as a proxy.",
        "",
    ]
    rows = []
    for workflow in WORKFLOWS:
        labels = results["labels"]["workflows"][workflow]
        rows.append(
            [
                f"`{workflow}`",
                num(labels["items"]),
                num(labels["adjudicated"]),
                num(labels["matching"]),
                num(labels["kappa_resolvable"], 2) if labels["kappa_resolvable"] is not None else NOT_DEFINED,
                labels["status"],
                pct(labels["share"]),
            ]
        )
    lines += _table(
        ["Workflow", "Items", "Adjudicated", "Matching the workflow", "Kappa", "Status", "Labeled share"], rows
    )
    export = results.get("labeling_export")
    if export:
        lines += [
            "",
            f"Labeling file: `{export['path']}` ({export['status']}; {num(export['items'])} items: "
            + ", ".join(f"{workflow} {num(count)}" for workflow, count in export["per_workflow"].items())
            + "). Machine pre-labels (review status `pending`, never used as labels) are in "
            f"`{export['prelabel_path']}`:",
            "",
        ]
        lines += _table(
            ["Stratum", "Pre-label topic", "Matches stratum", "Items"],
            [
                [f"`{stratum}`", topic, matches, num(count)]
                for stratum, topic, matches, count in export["prelabel_summary"]
            ],
        )
    lines += [
        "",
        "### Transcripts carry no workflow signal",
        "",
        f"{num(facts['transcripts'])} served transcripts hold {num(facts['distinct_customer_texts'])} distinct "
        "customer "
        f"texts; `detected_intents` has {num(facts['distinct_detected_intents'])} distinct value(s) "
        f"({', '.join(f'{value} {num(count)}' for value, count in transcripts['detected_intents'])}); `main_topics` "
        f"equals `contact_reason` on {num(facts['main_topics_equal_contact_reason'])} transcripts (a copy of the "
        "label, not an independent signal). The balance question in the customer text does not depend on the "
        "contact reason (Cramer's V "
        f"{num(transcripts['cramers_v_reason_by_opening'], 3)}; 0 means independence):",
        "",
    ]
    lines += _table(
        ["Contact reason", "Balance sentence of the customer text", "Transcripts"],
        [[reason, opening, num(count)] for reason, opening, count in transcripts["openings"]],
    )
    lines += [
        "",
        "Consequence: a human label on these texts measures a balance question, whatever the workflow stratum. The "
        "protocol therefore records whether the text matches the workflow, and only matching items count. For "
        "`card_support`, `dispute`, and `credit` the labels are expected to confirm that transcripts cannot measure "
        "the automatable share, and phase 10 needs team-authored or paraphrased utterances, labeled as such, to train "
        "and evaluate the router.",
        "",
    ]
    return lines


def _cost_section(results: Result) -> list[str]:
    costs = results["costs"]
    currency = costs["currency"]
    lines = [
        "## Cost baseline (projected, from assumptions)",
        "",
        "Handle cost = handled minutes (`duration_seconds`) times the assumed loaded cost per minute of the "
        "customer's country times the after-call-work factor. Contacts without a duration are costed at the "
        "workflow mean. Complaint back-office handling is not in the data and is excluded. The addressable cost is "
        "the last 365 days of handle cost times the automatable share: the label-based figure waits for human "
        "labels; the ceiling assumes a share of 100%; the proxy figure uses the structured proxy. None of these is "
        f"a measured saving. Window end: {costs['annual_window_end']}.",
        "",
    ]
    rows = []
    for workflow in WORKFLOWS:
        item = costs["workflows"][workflow]
        base = item["scenarios"]["1"]
        rows.append(
            [
                f"`{workflow}`",
                num(item["contacts"]),
                num(item["mean_handle_minutes"], 2),
                money(base["cost_per_contact"], currency),
                money(base["cost_per_resolved_contact"], currency),
                money(base["total_cost"], currency),
                money(base["annual_handle_cost"], currency),
                money(base["addressable_label_based"], currency),
                money(base["addressable_proxy"], currency),
            ]
        )
    lines += _table(
        [
            "Workflow",
            "Contacts",
            "Mean handled minutes",
            "Cost per contact",
            "Cost per resolved contact",
            "Total, full period",
            "Handle cost, last 365 days",
            "Addressable, label-based",
            "Addressable, proxy",
        ],
        rows,
    )
    lines += ["", "Sensitivity of the cost per resolved contact to the assumed loaded cost:", ""]
    multipliers = list(costs["workflows"][WORKFLOWS[0]]["scenarios"])
    lines += _table(
        ["Workflow", *[f"{multiplier} x" for multiplier in multipliers]],
        [
            [f"`{workflow}`"]
            + [
                money(costs["workflows"][workflow]["scenarios"][m]["cost_per_resolved_contact"], currency)
                for m in multipliers
            ]
            for workflow in WORKFLOWS
        ],
    )
    lines += [""]
    return lines


def _segments_section(results: Result) -> list[str]:
    lines = [
        "## Segment baseline",
        "",
        "Historical first contact resolution, escalation, and CSAT by country, detected accent, and customer "
        "segment: the reference values for the later disparity analysis. `small` marks cells under the "
        "pre-registered minimum of interactions or CSAT surveys.",
        "",
    ]
    for column, title in SEGMENT_DIMENSIONS:
        lines += [f"### {title}", ""]
        rows = [
            [
                row["group"],
                row["value"],
                num(row["interactions"]),
                pct(row["first_contact_resolution"]),
                pct(row["escalation"]),
                num(row["csat_mean"], 2),
                num(row["csat_surveys"]),
                "small" if row["small_cell"] else "",
            ]
            for row in results["segments"][column]
        ]
        lines += _table(
            [
                "Group",
                title,
                "Interactions",
                "First contact resolution",
                "Escalation",
                "CSAT mean",
                "CSAT surveys",
                "Cell",
            ],
            rows,
        )
        lines += [""]
    return lines


def _support_section(results: Result) -> list[str]:
    support = results["data_support"]
    lines = [
        "## Data support",
        "",
        "Measured coverage ratios behind the data support criterion (definitions in the pre-registration).",
        "",
    ]
    lines += _table(
        ["Item", "Definition", "Value"],
        [[f"`{name}`", item["description"], pct(item["value"])] for name, item in support["items"].items()],
    )
    lines += [
        "",
        "Per workflow (mean of its items): "
        + ", ".join(f"`{w}` {pct(support['workflows'][w])}" for w in WORKFLOWS)
        + ".",
        "",
    ]
    return lines


def _stop_section(results: Result) -> list[str]:
    stop = results["stop_conditions"]
    lines = ["## Stop conditions", ""]
    lines += _table(
        ["Check", "Result", "Evidence", "Workflows"],
        [
            [item["check"], "pass" if item["passed"] else "BLOCKED", item["detail"], item["workflows"]]
            for item in stop["checks"]
        ],
    )
    lines += [
        "",
        "No stop condition fired." if not stop["blocked"] else "Blocked: " + ", ".join(stop["blocked"]) + ".",
        "",
    ]
    return lines


def _evidence_limitations() -> list[str]:
    return [
        "## Limitations",
        "",
        "- The organizer data is fully synthetic. Several fields look generated independently of each other: "
        "complaint outcomes are flat across categories, sentiment is constant on transactional contacts, and "
        "transcripts are two templates. Differences between workflows come mostly from the contact reason.",
        "- The contact reasons are coarse; only `Transaccional` maps unambiguously. The strict and alternative "
        "scenarios show how much each conclusion depends on the mapping.",
        "- The automatable share is a structured proxy until humans label; the proxy measures historically simple "
        "contacts, not what the system can do.",
        "- Costs are projections from stated, unverified assumptions.",
        "- Timestamps are read as UTC (a phase 03 inference); local hours use fixed country offsets.",
    ]


# --------------------------------------------------------------------------------------------- scores


def render_scores(results: Result, meta: Result) -> str:
    scores = results["scores"]
    primary = scores["scenarios"]["primary"]
    lines = header(meta, "Workflow scores")
    lines += [
        "Computed exactly as pre-registered in "
        "[`workflow-scoring-preregistration.md`](workflow-scoring-preregistration.md) "
        "(`data_platform/analysis/scoring.yaml`). The decision that uses these numbers is "
        "[`docs/decisions/workflow-prioritization.md`](../decisions/workflow-prioritization.md). The automatable share "
        "is the structured proxy wherever the source column says so.",
        "",
        "## Weights",
        "",
    ]
    lines += _table(list(CRITERIA), [[num(scores["weights"][name]) for name in CRITERIA]])
    lines += ["", "## Criteria and scores (primary mapping)", ""]
    rows = []
    for workflow in primary["ranking"]:
        criteria = primary["criteria"][workflow]
        raw = primary["raw"][workflow]
        rows.append(
            [f"`{workflow}`"]
            + [num(criteria[name], 3) for name in CRITERIA]
            + [
                raw["automatable_source"],
                num(primary["scores"][workflow], 1),
                str(primary["ranking"].index(workflow) + 1),
            ]
        )
    lines += _table(["Workflow", *CRITERIA, "Automatable source", "Score", "Rank"], rows)
    lines += ["", "Raw inputs behind demand and pain:", ""]
    component_names = list(primary["raw"][WORKFLOWS[0]]["pain_components"])
    lines += _table(
        ["Workflow", "Contact share", *component_names, "Pain (mean)"],
        [
            [f"`{workflow}`", pct(primary["raw"][workflow]["demand_raw"])]
            + [num(primary["raw"][workflow]["pain_components"][name], 3) for name in component_names]
            + [num(primary["raw"][workflow]["pain_raw"], 3)]
            for workflow in WORKFLOWS
        ],
    )
    lines += ["", "![Pre-registered workflow scores](figures/scores.png)", "", "## Weight sensitivity", ""]
    sensitivity = scores["sensitivity"]
    lines += [
        f"Each weight moved by plus and minus the pre-registered delta and renormalized to 100: "
        f"{sensitivity['changed_variants']} of {len(sensitivity['variants'])} variants change the primary order.",
        "",
    ]
    lines += _table(
        ["Workflow", "Score range", "Rank range"],
        [
            [
                f"`{workflow}`",
                f"{num(sensitivity['ranges'][workflow]['score_min'], 1)} to "
                f"{num(sensitivity['ranges'][workflow]['score_max'], 1)}",
                f"{sensitivity['ranges'][workflow]['rank_min']} to {sensitivity['ranges'][workflow]['rank_max']}",
            ]
            for workflow in WORKFLOWS
        ],
    )
    lines += [""]
    lines += _table(
        ["Variant", "Order", "Changed"],
        [
            [variant["label"], ", ".join(variant["ranking"]), "yes" if variant["changed"] else ""]
            for variant in sensitivity["variants"]
        ],
    )
    lines += ["", "## Mapping sensitivity", ""]
    lines += _table(
        ["Scenario", *[f"`{w}`" for w in WORKFLOWS], "Order"],
        [
            [scenario]
            + [num(scores["scenarios"][scenario]["scores"][w], 1) for w in WORKFLOWS]
            + [", ".join(scores["scenarios"][scenario]["ranking"])]
            for scenario in SCENARIOS
        ],
    )
    lines += ["", "## Sub-intents", ""]
    rows = []
    for workflow in WORKFLOWS:
        members = [(name, row) for name, row in scores["sub_intents"].items() if row["workflow"] == workflow]
        for name, row in sorted(members, key=lambda item: (item[1].get("automation_order") or 99, -item[1]["score"])):
            rows.append(
                [
                    f"`{workflow}`",
                    f"`{name}`",
                    num(row["capability"], 1),
                    str(row["harm"]),
                    num(row["criteria"]["data_support"], 3),
                    num(row["score"], 1),
                    row["class"].replace("_", " "),
                    str(row.get("automation_order", "")),
                ]
            )
    lines += _table(
        ["Workflow", "Sub-intent", "Capability", "Harm", "Data support", "Score", "Class", "Automation order"], rows
    )
    stop = results["stop_conditions"]
    lines += [
        "",
        "## Stop conditions",
        "",
        "No stop condition fired." if not stop["blocked"] else "Blocked: " + ", ".join(stop["blocked"]) + ".",
        "",
        "The automatable share uses human labels only when a workflow has enough matching adjudicated items; "
        "otherwise it is the proxy. Label status: "
        + ", ".join(f"`{w}` {results['labels']['workflows'][w]['status']}" for w in WORKFLOWS)
        + f'. The label-based addressable cost reads "{PENDING}" until then.',
    ]
    return "\n".join(lines).rstrip() + "\n"
